package com.wmp.tool;

import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.TreeMap;

public class GetTranslate {
    public static String BASE_URL = "https://api.niutrans.com";
    public static String TRANSLATE_URL = BASE_URL + "/v2/text/translate";//翻译接口
    public static String apikey;//在'控制台->API应用'中查看
    public static String appId;//应用唯一标识,在'控制台->API应用'中查看

    public static void setAPIKey(String apiKey, String appId){
        GetTranslate.apikey = apiKey;
        GetTranslate.appId = appId;
    }


    /**
     * 获取翻译结果
     *
     * @return 翻译结果
     */
    public static String translate(String srcText, String from, String to) {
        TreeMap<String, Object> requestParamsMap = new TreeMap<>();
        requestParamsMap.put("from", from);
        requestParamsMap.put("to", to);
        requestParamsMap.put("srcText", srcText);
        requestParamsMap.put("appId", appId);
        requestParamsMap.put("apikey", apikey);
        requestParamsMap.put("timestamp", System.currentTimeMillis() + "");
        requestParamsMap.put("authStr", authStrGenerate(requestParamsMap));
        String result = null;
        try {
            result = HttpUtil.post(TRANSLATE_URL, requestParamsMap);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("翻译结果：" + result);
        return result;
    }

    //生成权限字符串
    public static String authStrGenerate(TreeMap<String, Object> requestParamsMap) {
        StringBuilder requestParamsStr = new StringBuilder();
        Set<String> keys = requestParamsMap.keySet();
        for (String key : keys) {
            requestParamsStr.append("&").append(key).append("=").append(requestParamsMap.get(key));
        }
        String paramsStr = requestParamsStr.toString().replaceFirst("&", "");
        requestParamsMap.remove("apikey");
        return SecureUtil.md5(paramsStr);
    }
}

class LanguageList {
    public static final List<String[]> LANGUAGES = Arrays.asList(new String[][] {
            {"法兰克-普罗旺斯语", "Franco-Provençal", "frp"},
            {"梵语", "Sanskrit", "sa"},
            {"高棉语", "Khmer", "km"},
            {"盖丘亚语", "Quichua", "quw"},
            {"刚果语", "Kikongo", "kg"},
            {"弗里西语", "Frisian", "fy"},
            {"格鲁吉亚语", "Georgian", "jy"},
            {"古吉拉特语", "Gujarati", "gu"},
            {"瓜哈哈拉语", "Guajajára", "gub"},
            {"果发语", "Goffa", "gof"},
            {"格森语", "Kasem", "xsm"},
            {"格巴亚语", "Gbaya", "krs"},
            {"龚语", "Gun", "guw"},
            {"刚果斯瓦希里语", "Congo Swahili", "swc"},
            {"圭米语", "Guaymí", "gym"},
            {"瓜拉尼语", "Guarani", "gn"},
            {"格陵兰语", "Kalaallisut", "kl"},
            {"高原马达加斯加语", "Plateau Malagasy", "plt"},
            {"古英语", "Old English", "ang"},
            {"哈萨克语", "Kazakh", "ka"},
            {"哈萨克语(西里尔)", "Kazakh(Cyrillic)", "kk"},
            {"海地克里奥尔语", "Haitian Creole", "ht"},
            {"韩语", "Korean", "ko"},
            {"豪萨语", "Hausa", "ha"},
            {"荷兰语", "Dutch", "nl"},
            {"黑山语", "Montenegrin", "me"},
            {"哈卡钦语", "Hakha Chin", "cnh"},
            {"胡里语", "Huli", "hui"},
            {"亥比语", "Halbi", "hlb"},
            {"赫雷罗语", "Herero", "her"},
            {"胡帕语", "Hupa", "hup"},
            {"吉尔吉斯语", "Kyrgyz", "ky"},
            {"基切语", "Kiche", "quc"},
            {"加莱拉语", "Galela", "gbi"},
            {"加利西亚语", "Galician", "gl"},
            {"加泰罗尼亚语", "Catalan", "ca"},
            {"捷克语", "Czech", "cs"},
            {"基里巴斯语", "Kiribati", "gil"},
            {"景颇语", "Jingpho", "kac"},
            {"加语", "Ga", "gaa"},
            {"基库尤语", "Kikuyu", "kik"},
            {"金邦杜语", "Kimbundu", "kmb"},
            {"加利富纳语", "Garifuna", "cab"},
            {"加拿大法语", "Canadian French", "fr-CA"},
            {"卡拜尔语", "Kabyle", "kab"},
            {"卡韦卡尔语", "Cabecar", "cjp"},
            {"卡克奇克尔语", "Cakchiquel", "cak"},
            {"卡纳达语", "Kannada", "kn"},
            {"凯克其语", "Qeqchi", "kek"},
            {"坎帕语", "Campa", "cni"},
            {"科普特语", "Coptic", "cop"},
            {"科奇语", "Camsa", "kbh"},
            {"科西嘉语", "Corsican", "co"},
            {"克雷塔罗奥托米语", "Queretaro Otomi", "otq"},
            {"克罗地亚语", "Croatian", "hr"},
            {"库尔德语(库尔曼奇语)", "Kurdish(Kurmanji)", "ku"},
            {"库尔德语(索拉尼语)", "Kurdish(Sorani)", "ckb"},
            {"库阿努阿语", "Kuanua", "ksd"},
            {"库斯科克丘亚语", "Cusco Quechua", "quz"},
            {"卡平阿马朗伊语", "Kapingamarangi", "kpg"},
            {"克里米亚鞑靼语", "Crimean Tatar", "crh"},
            {"卡尔梅克卫拉特语", "Kalmyk-Oirat", "xal"},
            {"克利科语", "Keliko", "kbo"},
            {"卡库瓦语", "Kakwa", "keo"},
            {"喀克其奎语", "Kaqchikel", "cki"},
            {"卡乌龙语", "Kaulong", "pss"},
            {"库隆语", "Kulung", "kle"},
            {"卡纳尔高地-基丘亚语", "Cañar HighlandQuichua", "qxr"},
            {"库克群岛毛利语", "Cook Islands Māori", "rar"},
            {"卡比耶语", "Kabiye", "kbp"},
            {"卡姆巴语", "Kamba", "kam"},
            {"卡昂多语", "Kaonde", "kqn"},
            {"喀麦隆皮钦语", "Cameroonian Pidgin", "wes"},
            {"宽亚玛语", "Kwanyama", "kua"},
            {"克林贡语", "Klingon", "tlh"},
            {"卡努里语", "Kanuri", "kr"},
            {"康沃尔语", "Cornish", "kw"},
            {"卡舒比语", "Kashubian", "csb"},
            {"卢旺达语", "Kinyarwanda", "rw"},
            {"拉丁语", "Latin", "la"},
            {"拉脱维亚语", "Latvian", "lv"},
            {"老挝语", "Lao", "lo"},
            {"隆迪语", "Kirundi", "rn"},
            {"立陶宛语", "Lithuanian", "lt"},
            {"林加拉语", "Lingala", "ln"},
            {"卢干达语", "Luganda", "lg"},
            {"卢克帕语", "Lukpa", "dop"},
            {"卢森堡语", "Luxembourgish", "lb"},
            {"罗马尼亚语", "Romanian", "ro"},
            {"罗姆语", "Romani", "rmn"},
            {"隆韦语", "Lomwe", "ngl"},
            {"罗维那语", "Roviana", "rug"},
            {"勒期语", "Lacid", "lsi"},
            {"临高语", "Lingao", "ond"},
            {"罗子语", "Lozi", "loz"},
            {"卢巴开赛语", "Luba-Kasai", "lua"},
            {"卢巴-加丹加语", "Luba-Katanga", "lub"},
            {"隆打语", "Lunda", "lun"},
            {"卢乌德语", "Ruund", "rnd"},
            {"卢瓦来语", "Luvale", "lue"},
            {"林堡语", "Limburgs", "li"},
            {"逻辑语", "Lojban", "jbo"},
            {"马尔加什语", "Malagasy", "mg"},
            {"马耳他语", "Maltese", "mt"},
            {"马恩岛语", "Manx", "gv"},
            {"马拉地语", "Marathi", "mr"},
            {"马拉雅拉姆语", "Malayalam", "ml"},
            {"马来语", "Malay", "ms"},
            {"马里语", "Mari", "mhr"},
            {"马姆语", "Mam", "mam"},
            {"马其顿语", "Macedonian", "mk"},
            {"毛利语", "Maori", "mi"},
            {"蒙古语", "Mongolian", "mo"},
            {"蒙古语(西里尔)", "Mongolian(Cyrillic)", "mn"},
            {"缅甸语", "Burmese", "my"},
            {"孟加拉语", "Bengali", "bn"},
            {"曼尼普尔语", "Manipuri", "mni"},
            {"摩图语", "Motu", "meu"},
            {"马绍尔语", "Marshallese", "mah"},
            {"马拉瑙语", "Maranao", "mrw"},
            {"马勒语", "Maale", "mdy"},
            {"马都拉语", "Madurese", "mad"},
            {"莫西语", "Mossi", "mos"},
            {"穆图凡语", "Muthuvan", "muv"},
            {"米佐语", "Mizo", "lus"},
            {"毛里求斯克里奥尔语", "Mauritian Creole", "mfe"},
            {"姆班杜语", "Umbundu", "umb"},
            {"马普切语", "Mapuche", "arn"},
            {"米斯特克语", "Metlatónoc Mixtec", "mxv"},
            {"马库阿语", "Makhuwa", "vmw"},
            {"曼代灵西马隆贡语", "Batak Simalungun", "bts"},
            {"曼布韦-龙古语", "Mambwe-Lungu", "mgr"},
            {"门诺低地德语", "Plautdietsch", "pdt"},
            {"米兰达语", "Mirandese", "mwl"},
            {"迈蒂利语", "Maithili", "mai"},
            {"马来语克里奥尔语", "Malay trade andcreole", "crp"},
            {"纳瓦特尔语", "Nahuatl", "nhg"},
            {"南非荷兰语", "Afrikaans", "af"},
            {"南非科萨语", "Xhosa", "xh"},
            {"南非祖鲁语", "Zulu", "zu"},
            {"尼泊尔语", "Nepali", "ne"},
            {"挪威语", "Norwegian", "no"},
            {"南阿塞拜疆语", "South Azerbaijani", "azb"},
            {"南玻利维亚克丘亚语", "South BolivianQuechua", "quh"},
            {"弄巴湾语", "Lun Bawang", "lnd"},
            {"尼日利亚富拉语", "Nigerian Fulfulde", "fuv"},
            {"努曼干语", "Numanggang", "nop"},
            {"纳特尼语", "Nateni", "ntm"},
            {"尼亚库萨语", "Nyakyusa", "nyy"},
            {"纽埃语", "Niuean", "niu"},
            {"尼亚斯语", "Nias", "nia"},
            {"涅姆巴语", "Nyemba", "nba"},
            {"尼荣圭语", "Nyungwe", "nyu"},
            {"纳瓦霍语", "Navajo", "nav"},
            {"尼亚内卡语", "Nyaneka", "nyk"},
            {"尼日利亚皮钦语", "Nigerian Pidgin", "pcm"},
            {"南恩德贝莱语", "Southern Ndebele", "nr"},
            {"帕皮阿门托语", "Papiamento", "pap"},
            {"派特语", "Paite", "pck"},
            {"旁遮普语", "Punjabi", "pa"},
            {"葡萄牙语", "Portuguese", "pt"},
            {"普什图语", "Pashto", "ps"},
            {"佩勒-阿塔语", "Pele-Ata", "ata"},
            {"皮京语", "Pijin", "pis"},
            {"帕潘特拉托托纳克语", "Papantla Totonac", "top"},
            {"齐切瓦语", "Chewa", "ny"},
            {"契维语", "Twi", "tw"},
            {"切诺基语", "Cherokee", "chr"},
            {"奇南特克语", "Chinantec", "chq"},
            {"齐马内语", "Tsimané", "cas"},
            {"乔奎语", "Chokwe", "cjk"},
            {"乔皮语", "Chopi", "cce"},
            {"丘克语", "Chuukese", "chk"},
            {"钦博拉索高地克丘亚语", "Chimborazo HighlandQuichua", "qug"},
            {"恰蒂斯加尔语", "Chhattisgarhi", "hne"},
            {"日语", "Japanese", "ja"},
            {"瑞典语", "Swedish", "sv"},
            {"萨摩亚语", "Samoan", "sm"},
            {"塞尔维亚语", "Serbian", "sr"},
            {"塞舌尔克里奥尔语", "Seychelles Creole", "crs"},
            {"塞索托语", "Sesotho", "st"},
            {"桑戈语", "Sango", "sg"},
            {"僧伽罗语", "Sinhalese", "si"},
            {"山地马里语", "Hill Mari", "mrj"},
            {"世界语", "Esperanto", "eo"},
            {"舒阿尔语", "Shuar", "jiv"},
            {"斯洛伐克语", "Slovak", "sk"},
            {"斯洛文尼亚语", "Slovenian", "sl"},
            {"斯瓦希里语", "Swahili", "sw"},
            {"苏格兰盖尔语", "Scottish Gaelic", "gd"},
            {"索马里语", "Somali", "so"},
            {"苏奥语", "Suau", "swp"},
            {"桑贝里吉语", "Samberigi", "ssx"},
            {"萨鲍特语", "Sabaot", "spy"},
            {"圣马特奥德马尔-瓦维语", "San Mateo del MarHuave", "huv"},
            {"斯哈语", "Kisiha", "jmc"},
            {"萨拉马坎语", "Saramaccan", "srm"},
            {"桑格语", "Sangir", "sxn"},
            {"塞纳语", "Sena", "seh"},
            {"圣萨尔瓦多刚果语", "San Salvador Kongo", "kwy"},
            {"松格语", "Songe", "sop"},
            {"索西语", "Tzotzil", "tzo"},
            {"斯高克伦语", "S'gaw Karen", "ksw"},
            {"苏格兰语(低地苏格兰语)", "sco (Scots)", "sco"},
            {"书面挪威语", "Bokmål", "nb"},
            {"撒丁语", "Sardinian", "sc"},
            {"掸语", "Shan", "shn"},
            {"塞尔维亚-克罗地亚语", "Serbo-Croatian", "sh"},
            {"斯威士语", "Swazi", "ss"},
            {"上索布语", "Upper Sorbian", "hsb"},
            {"塔吉克语", "Tajik", "tg"},
            {"塔希提语", "Tahitian", "ty"},
            {"泰卢固语", "Telugu", "te"},
            {"泰米尔语", "Tamil", "ta"},
            {"泰语", "Thai", "th"},
            {"汤加语", "Tongan", "to"},
            {"提格雷语", "Tigre", "tig"},
            {"图阿雷格语", "Tamajaq", "tmh"},
            {"土耳其语", "Turkish", "tr"},
            {"土库曼语", "Turkmen", "tk"},
            {"坦普尔马语", "Tampulma", "tpm"},
            {"特丁钦语", "Tedim Chin", "ctd"},
            {"图瓦语", "Tuvan", "tyv"},
            {"图马伊鲁穆语", "Tuma-Irumu", "iou"},
            {"腾内特语", "Tennet", "tex"},
            {"通加格语", "Tungag", "lcm"},
            {"特索语", "Teso", "teo"},
            {"图瓦卢语", "Tuvaluan", "tvl"},
            {"特特拉语", "Tetela", "tll"},
            {"他加禄语", "Tagalog", "tgl"},
            {"通布卡语", "Tumbuka", "tum"},
            {"托霍拉瓦尔语", "Tojolabal", "toj"},
            {"土柔语", "Tooro", "ttj"},
            {"瓦拉莫语", "Wolaytta", "wal"},
            {"瓦瑞语", "Waray", "war"},
            {"文达语", "Venda", "ve"},
            {"沃洛夫语", "Wolof", "wol"},
            {"乌德穆尔特语", "Udmurt", "udm"},
            {"乌尔都语", "Urdu", "ur"},
            {"乌克兰语", "Ukrainian", "uk"},
            {"乌兹别克语", "Uzbek", "uz"},
            {"乌玛语", "Uma", "ppk"},
            {"乌斯潘坦语", "Uspanteco", "usp"},
            {"瓦利语", "Wali", "wlx"},
            {"佤语", "Wa", "prk"},
            {"瓦吉语", "Waskia", "wsk"},
            {"瓦里斯语", "Waris", "wrs"},
            {"文约语", "Vunjo", "vun"},
            {"威尔士语", "Welsh", "cy"},
            {"瓦利斯语", "Wallisian", "wls"},
            {"乌尔霍博语", "Urhobo", "urh"},
            {"瓦乌特拉马萨特克语", "Huautla Mazatec", "mau"},
            {"瓦尤语", "Wayuu", "guc"},
            {"瓦隆语", "Walon", "wa"},
            {"西班牙语", "Spanish", "es"},
            {"希伯来语", "Hebrew", "he"},
            {"希尔哈语", "Tachelhit", "shi"},
            {"希腊语", "Greek", "el"},
            {"夏威夷语", "Hawaiian", "haw"},
            {"信德语", "Sindhi", "sd"},
            {"匈牙利语", "Hungarian", "hu"},
            {"修纳语", "Shona", "sn"},
            {"宿务语", "Cebuano", "ceb"},
            {"叙利亚语", "Syriac", "syc"},
            {"夏威夷克里奥尔英语", "Hawaiian CreoleEnglish", "hwc"},
            {"希里莫图语", "Hiri Motu", "hmo"},
            {"西部拉威语", "Western Lawa", "lcp"},
            {"锡达莫语", "Sidamo", "sid"},
            {"西布基农马诺布语", "Western BukidnonManobo", "mbb"},
            {"西皮沃语", "Shipibo", "shp"},
            {"西罗伊语", "Siroi", "ssd"},
            {"西部玻利维亚瓜拉尼语", "Western BolivianGuarani", "gnw"},
            {"西部克耶语", "Western Kayah", "kyu"},
            {"希利盖农语", "Hiligaynon", "hil"},
            {"新挪威语", "Nynorsk", "nn"},
            {"下索布语", "Lower Sorbian", "dsb"},
            {"新通用语", "Lingua Franca Nova", "lfn"},
            {"西方国际语", "Interlingue", "ie"},
            {"亚美尼亚语", "Armenian", "hy"},
            {"雅加达语", "Jakalteko", "jac"},
            {"亚齐语", "Aceh", "ace"},
            {"伊博语", "Igbo", "ig"},
            {"意大利语", "Italian", "it"},
            {"意第绪语", "Yiddish", "yi"},
            {"印地语", "Hindi", "hi"},
            {"印尼巽他语", "Sundanese", "su"},
            {"印尼语", "Indonesian", "id"},
            {"印尼爪哇语", "Javanese", "jv"},
            {"英语", "English", "en"},
            {"尤卡坦玛雅语", "Yucatec Maya", "yua"},
            {"约鲁巴语", "Yoruba", "yo"},
            {"越南语", "Vietnamese", "vi"},
            {"粤语", "Cantonese", "yue"},
            {"伊卡语", "Ika", "ikk"},
            {"伊兹语", "Izi", "izz"},
            {"约姆语", "Yom", "pil"},
            {"雅比姆语", "Yabem", "jae"},
            {"永贡语", "Yongkom", "yon"},
            {"邕北壮语", "Yongbei Zhuang", "zyb"},
            {"伊普马语", "Yipma", "byr"},
            {"伊索科语", "Isoko", "iso"},
            {"伊班语", "Iban", "iba"},
            {"伊洛卡诺语", "Ilocano", "ilo"},
            {"伊巴纳格语", "Ibanag", "ibg"},
            {"雅浦语", "Yapese", "yap"},
            {"因巴布拉高地克丘亚语", "Imbabura HighlandQuichua", "qvi"},
            {"伊多语", "Ido", "io"},
            {"因特语", "Interlingua", "ia"},
            {"哲尔马语", "Zarma", "dje"},
            {"中文(简体)", "Chinese (Simplified)", "zh"},
            {"中文(繁体)", "Chinese (Traditional)", "cht"},
            {"宗喀语", "Dzongkha", "dz"},
            {"中部伊富高语", "Central Ifugao", "ifa"},
            {"佐通钦语", "Zotung Chin", "czt"},
            {"中部杜顺语", "Central Dusun", "dtp"},
            {"中比科尔语", "Central Bikol", "bcl"},
            {"泽塔尔语", "Tzeltal", "tzh"},
            {"赞德语", "Zande", "zne"},
            {"中部普埃布拉纳瓦特语", "Central PueblaNahuatl", "ncx"},
            {"中部瓦斯特克纳瓦特语", "Central HuastecaNahuatl", "nch"},
            {"中古法语", "Middle French", "frm"}
    });

    public static TreeMap<String, String> getLanguageMap() {
        TreeMap<String, String> map = new TreeMap<>();
        for (String[] language : LANGUAGES) {
            map.put(language[0], language[2]);
        }
        return map;
    }
}
